### ISSUE TITLE
Missing routing file

### ISSUE THREAD

**Issue by lbenicio** [ethkat/tibia-ts3-teamspeakbot#14]
modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:231 Uncaught Error: Cannot find module '/imports/startup/client/Routes'

at /imports/startup/client/index.js request a /imports/startup/client/Routes which is not present

**Comment by Ethaan** [comment]
Hmm this was a bug which was supposted to be fixed, just do.

`/imports/startup/client/Routes` => `/imports/startup/client/routes` (note lowercase on R) will fix this as soon i get into home

**Comment by lbenicio** [comment]
thank for the incredibly fast reply, i was able to fix it! 

But went into another error which my Chrome Console returns as: Uncaught Error: Cannot find module '/imports/ui/pages/LandingPage/LandingPage', so i checked the directory /imports/ui/pages/LandingPage/ which do not has subfolder LandingPage neither a LandingPage file

**Comment by Ethaan** [comment]
Hmm what OS do you use?

**Comment by lbenicio** [comment]
Was just missing directory, index was trying to load a module where there wasn't none, a just replaced the directories and everything worked fine. But i'm currently using macOS High Sierra. 

Since i'm not using the bot anyone, i will close this issue
