### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by Kuhicop** [ethkat/tibia-ts3-teamspeakbot#15]
https://gyazo.com/341a3ef5ec167b9f1ca77758a5310c4c
https://gyazo.com/dd4254d1075925fba19585d4aa4d0f2a

Your app is crashing. Here's the latest log:
=> A patch (Meteor 1.5.4) for your current release is available!
   Update this project now with 'meteor update --patch'.
Errors prevented startup:

While preparing to run:
settings/development.json: file not found (settings file)

Your application has errors. Waiting for file change.
Started MongoDB.

**Comment by Ethaan** [comment]
There are 2 ways of fixing this issue.

1.- inside `package.json` on the `scripts` section the `dev` script remove the `--setings` so it just be like `"dev": "meteor",`

2.- Create a folder with an empty folder named `settings.json` like `settings/development.json`

**Comment by Kuhitacop** [comment]
https://gyazo.com/e5de264ff93ca302199a65c9100d1104

**Comment by Ethaan** [comment]
`development.json` is supossed to be private, but let me create one for you

**Comment by Kuhitacop** [comment]
Do you have it bro?

**Comment by Ethaan** [comment]
Here is an example.

```
{
  "TEST_DATA": [{
    "bot": {
      "address": "teamspeak",
      "port": 13002,
      "serverId": "1"
    },
    "user": {
      "username": "ETHANBOT",
      "password": "password"
    },
    "server": "medivia"
  }]
}

```

**Comment by Kuhitacop** [comment]
Hello sir, 
username and password fields are for??

**Comment by Ethaan** [comment]
Server query login, its easy but you need to be sure you have the correct privilegies to create accounts, check out [this link](https://www.teamspeak3.com/support/teamspeak-3-add-server-query-user.php)

**Comment by Kuhitacop** [comment]
Oh yes I know what is! Thanks <3 I will try when the admin of ts is online as I'm just making this to help a friend
Thank you bro, do you have any character in Legacy or Pendulum?

**Comment by Ethaan** [comment]
I was playing on Legacy under Ethaanpump char, but i got kicked by damodres, on Pendu im etjanpump, just play the first 2 days, get 60lvl and retired, i don't have much time

**Comment by Kuhitacop** [comment]
If you go back to Legacy answer here with your name and I will send some love by parcel <3 :D

**Comment by Ethaan** [comment]
@Kuhicop you got this working? i'm planning to work in a new version soon of this
