### ISSUE TITLE
Errors prevented startup:

### ISSUE THREAD

**Issue by anisiovalverde** [ethkat/tibia-ts3-teamspeakbot#17]
Errors prevented startup:

While preparing to run:
settings/development.json: file not found (settings file)

Your application has errors. Waiting for file change.
Started MongoDB.

**Comment by Ethaan** [comment]
Hello @anisiovalverde this means you don't have a file named `development.json` under your PC, do you have a Teamspeak server where i can connect and explain you this

**Comment by Ethaan** [comment]
Check this issue.

https://github.com/ethkat/tibia-ts3-teamspeakbot/issues/15

**Comment by anisiovalverde** [comment]
yes i have but im at work right now can you give the content and i will change by my self to put it to work

**Comment by Ethaan** [comment]
This should be changed with your data.

```
{
  "TEST_DATA": [{
    "bot": {
      "address": "teamspeak",
      "port": 13002,
      "serverId": "1"
    },
    "user": {
      "username": "ETHANBOT",
      "password": "password"
    },
    "server": "medivia"
  }]
}
```

**Comment by anisiovalverde** [comment]
Your app is crashing. Here's the latest log:
Errors prevented startup:

While preparing to run:
settings/development.json: parse error reading settings file

Your application has errors. Waiting for file change.
Started MongoDB.



> Changes

{
  "TEST_DATA": [{
    "bot": {
      "address": "127.0.0.1",
      "port": 10011,
      "serverId": "1"
    },
    "user": {
      "username": "serveradmin",
      "password": "*******"
    },
    "server": "tibia"
  }]
}

**Comment by Ethaan** [comment]
Seems like correct to me.

![screen shot 2017-12-12 at 10 04 34 am](https://user-images.githubusercontent.com/8289486/33894329-524549e2-df23-11e7-811e-736f2e2f8706.png)

**Comment by anisiovalverde** [comment]
can i give to you remote access ?

**Comment by Ethaan** [comment]
i can try tonight, not now

**Comment by anisiovalverde** [comment]
ok my last file 

{
  "teamspeak": [{
    "bot": {
      "address": "127.0.0.1",
      "port": "10011",
      "serverId": "1"
    },
    "user": {
      "username": "serveradmin",
      "password": "*****"
    },
    "server": "medivia"
  }]
}



Error

Your app is crashing. Here's the latest log:
Errors prevented startup:

While preparing to run:
settings/development.json: parse error reading settings file

Your application has errors. Waiting for file change.

**Comment by anisiovalverde** [comment]
if i delete like you said in another issue  --settings settings/development.json
i only get white pages

**Comment by anisiovalverde** [comment]
last problem 

=> A patch (Meteor 1.5.4.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
Started MongoDB.
Errors prevented startup:

While processing files with fourseven:scss (for target web.browser):
/client/main.scss: Scss compiler error: File to import: {}/node_modules/bootstrap/scss/bootstrap.scss not found in file: C:/Users/Administrator/Downloads/tibia-ts3-teamspeakbot-master/{}/client/main.scss


Your application has errors. Waiting for file change.

**Comment by anisiovalverde** [comment]
i still wait for a solution on 
\\
Your app is crashing. Here's the latest log:
Errors prevented startup:

While preparing to run:
settings/development.json: parse error reading settings file

Your application has errors. Waiting for file change.

**Comment by Ethaan** [comment]
@anisiovalverde if you still play tibia and need a bot,
