### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by snop3252** [ethkat/tibia-ts3-teamspeakbot#19]
$ meteor --settings  settings/development.json
[[[[[ ~/tibia-ts3-teamspeakbot ]]]]]          

=> Started proxy.                             
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Unexpected mongo exit code 14. Restarting.    
Unexpected mongo exit code 14. Restarting.    
Unexpected mongo exit code 14. Restarting.    
Can't start Mongo server.                     
Unspecified unrecoverable error. Exit was not clean
error Command failed with exit code 254.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

can anybody help me?

**Comment by Ethaan** [comment]
@snop3252 its been 2 years since i don't touch this code and the teamspeak API has changed, which makes making a bot easier, let me work on a new version of this
