### ISSUE TITLE
Cannot change bot's nickname

### ISSUE THREAD

**Issue by jotavf** [ethkat/tibia-ts3-teamspeakbot#33]
Hi, @Ethaan !

Dude, many ways I've tried to change bot's nickname but unsuccessful...
I've tried to set it on .env, explicited on init.js without import from constants, searched if there's a way to change in teamspeak files... and either unsuccessful...

I would like to change this: https://prnt.sc/se7cjr

**Comment by Ethaan** [comment]
I need to re-check this, did you find a way?
